### ISSUE TITLE
Please bring sci-wms development back to github!

### ISSUE THREAD

**Issue by rsignell-usgs** [asascience-open/sci-wms#124]
It would appear that in mid-July of 2014, the development of sci-wms went private.   There was healthy discussion and updates by a number of contributors, and now  nothing public since mid-July.    

Can we please bring the development back?  

 I think development supported by IOOS should be here on github where the community can participate.    

Certainly sci-wms has benefited from a lot of community development!

@kknee @EoinHowlett, what say ye?

**Comment by EoinHowlett** [comment]
We'll publish a version to a COMT branch by Monday next week.
Thanks
Eoin

**Comment by rsignell-usgs** [comment]
@EoinHowlett , awesome!     I am (slowly) coming to understand the reasons for sometimes taking the development of open source projects private, but hopefully in this case, it will be the win-win that I think it will be -- the software and your developers will benefit from interacting with a larger community, and the larger community will benefit from the software!

**Comment by brianmckenna** [comment]
[comt_testbed](https://github.com/asascience-open/sci-wms/tree/comt_testbed) branch has been restored.

Several developmental gaps remain unaddressed in the comt_testbed branch as it's development was focused on specific requirements:

* GetCapabilities did not function for ANY unstructured grids. Due to the way the COMT UI was designed (to support menus), GetCapabilites was not used. A non-WMS JSON endpoint was created similar to what ncWMS does for Godiva. I've begun restoring GetCapabilities functionality, but it is not complete.

* A large amount of development for COMT was to follow the CF specification of standard_name to
> allow users of data from different sources to determine whether quantities were in fact comparable

__http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/cf-conventions.html#standard-name__
Thus, support for all variables in a DAP endpoint using the internal NetCDF variable name and long_name, as was being done previously and is done by ncWMS, was not a priority and remains nonfunctional. Only variables with known COMT relevant standard_names are loaded in this branch.

* COMT datasets are loaded via NGDC catalog, thus, the admin page does not function as expected in this branch.
